// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGKca509XEcmigLVm4QMNefURsHDllWQw',
    appId: '1:523686545504:web:99e94a4a11377c892a5b05',
    messagingSenderId: '523686545504',
    projectId: 'od-management-59dbc',
    authDomain: 'od-management-59dbc.firebaseapp.com',
    storageBucket: 'od-management-59dbc.firebasestorage.app',
    measurementId: 'G-BJWLGKZGXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu6nyooeyCCEhQPfp6hKVthfjsTAxnIAk',
    appId: '1:523686545504:android:d0bf54240581875e2a5b05',
    messagingSenderId: '523686545504',
    projectId: 'od-management-59dbc',
    storageBucket: 'od-management-59dbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOURk4l3IA6Z7mDOgXWKjJF-hitSujRFY',
    appId: '1:523686545504:ios:c7cf9e9bdf1cd1662a5b05',
    messagingSenderId: '523686545504',
    projectId: 'od-management-59dbc',
    storageBucket: 'od-management-59dbc.firebasestorage.app',
    iosBundleId: 'com.example.od',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGKca509XEcmigLVm4QMNefURsHDllWQw',
    appId: '1:523686545504:web:4668823d136953ac2a5b05',
    messagingSenderId: '523686545504',
    projectId: 'od-management-59dbc',
    authDomain: 'od-management-59dbc.firebaseapp.com',
    storageBucket: 'od-management-59dbc.firebasestorage.app',
    measurementId: 'G-9909GCTPPJ',
  );
}
